// ctm — OpenCode ↔ Telegram pipe. Generated by ctm __CTM_VERSION__. Do not edit:
// `ctm doctor --fix` (and the ctm daemon itself) rewrite this file when ctm updates.
//
// Runs inside every OpenCode process (TUI, `serve`, `web`). It forwards OpenCode's
// event bus to the ctm daemon over a local Unix socket and executes the API calls the
// daemon sends back through OpenCode's own in-process client — so a bare `opencode`
// is mirrored with no --port, no password, and nothing to configure. When ctm is not
// running this does nothing and retries quietly. It never writes to the terminal.
//
// Wire protocol (NDJSON, one object per line):
//   up:   {"ctm":"opencode","v":1,"pid","serverUrl","directory","worktree","project"}  hello
//         {"type":"event","event":<OpenCode bus event>}
//         {"type":"result","id","status","data","error"}
//   down: {"type":"call","id","method","url","query","body"}
import net from "node:net"

const SOCKET = "__CTM_PIPE_SOCKET__"

export default async function ctm(input) {
  if (process.env.CTM_OPENCODE_PIPE === "0") return {}
  const st = { sock: null, buf: "" }
  const send = (o) => {
    const s = st.sock
    if (s && !s.destroyed) {
      try { s.write(JSON.stringify(o) + "\n") } catch {}
    }
  }
  // Never touch the client inside init: the server finishes constructing after init
  // returns, and a call made before that deadlocks the TUI (spike-verified).
  setTimeout(() => { pipe(input, st, send).catch(() => {}) }, 0)
  // The event hook is fed from the bus in-process and carries the full superset
  // (permission.asked, question.asked, message.*, session.*), unlike event.subscribe().
  return { event: async ({ event }) => { send({ type: "event", event }) } }
}

async function pipe(input, st, send) {
  const raw = input.client._client
  let delay = 1000
  const hello = () => ({
    ctm: "opencode", v: 1, pid: process.pid,
    serverUrl: String(input.serverUrl ?? ""),
    directory: input.directory ?? "", worktree: input.worktree ?? "",
    project: input.project?.id ?? "",
  })
  const onLine = (line) => {
    let m
    try { m = JSON.parse(line) } catch { return }
    if (m?.type !== "call") return
    raw.request({ method: m.method, url: m.url, query: m.query ?? undefined, body: m.body ?? undefined })
      .then((r) => send({ type: "result", id: m.id, status: r.response?.status ?? 0, data: r.data ?? null, error: r.error ?? null }))
      .catch((e) => send({ type: "result", id: m.id, status: 0, data: null, error: String(e) }))
  }
  const connect = () => new Promise((resolve) => {
    const s = net.createConnection(SOCKET)
    s.once("connect", () => {
      st.sock = s; st.buf = ""; delay = 1000
      s.write(JSON.stringify(hello()) + "\n")
      resolve(true)
    })
    s.once("error", () => resolve(false))
    s.on("data", (d) => {
      st.buf += d.toString("utf8")
      let i
      while ((i = st.buf.indexOf("\n")) >= 0) {
        const l = st.buf.slice(0, i)
        st.buf = st.buf.slice(i + 1)
        onLine(l)
      }
    })
    s.on("close", () => { if (st.sock === s) st.sock = null })
  })
  for (;;) {
    if (!st.sock) {
      if (!(await connect())) {
        await new Promise((r) => setTimeout(r, delay))
        delay = Math.min(delay * 2, 30000)
        continue
      }
    }
    await new Promise((r) => { const s = st.sock; s ? s.once("close", r) : r() })
  }
}
